### ISSUE TITLE
Docker-Compose instance downloads not showing up

### ISSUE THREAD

**Issue by ignition-ctrl** [recodeuk/youtube-dl-flask#10]
Running this docker-compose file
```
version: "3.0"
services:
        youtube-dl:
                image: recodeuk/youtube-dl-flask
                volumes:
                   - /home/core/youtube-dl:/youtube-dl
                restart: always
                ports:
                        - 8080:8080
```
Allows me to access `localhost:8080/youtube-dl`. However, when I try a link, there's no indication of where the downloads are. I checked `/home/core/youtube-dl/` but it's empty. Do I need to mount another volume? I couldn't find any other documentation on this
